spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: 'jdbc:h2:file:~/thetabot-h2-db;AUTO_SERVER=TRUE'
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
  thymeleaf:
    prefix: classpath:/templates/
# The format used for the keystore. It could be set to JKS in case it is a JKS file
server:
  port: 443
  ssl:
    key-store-type: PKCS12
    # The path to the keystore containing the certificate
    key-store: classpath:keystore/thetabot.p12
    # The password used to generate the certificate
    key-store-password: 
    # The alias mapped to the certificate
    key-alias: thetabot